modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="saidifficulty" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SaiDifficulty" #mandatory
logoFile="icon.png" #optional
credits="NathanSaidas" #optional
authors="NathanSaidas" #optional
description='''
This mod allows you to add additional difficulty by scaling the mobs health/damage/armor etc based on distance from 'spawn' (0,0,0).

This mod also allows you to provide additional loot drops via LootTables based on distance from 'spawn' (0,0,0)
'''
[[dependencies.saidifficulty]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.saidifficulty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
